<?php

use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        // DB::table('users')->insert([
        //     'name' => 'Admin',
        //     'email' => 'admin0@admin.com',
        //     'mobile' => '01787408231',
        //     'blood_group' => 'O+',
        //     'country' => 'Bangladesh',
        //     'city' => 'Natore',
        //     'district' => 'Natore',
        //     'thana' => 'Singra',
        //     'area' => 'Singra',
        //     'last_donate_time' => 'NULL',
        //     'state' => ' ',
        //     'address' => 'Singra,Natore',
        //     'status' => '0',
        //     'profile_picture' => 'NULL',
        //     'type' => 'admin',
        //     'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        // ]);


        DB::table('users')->insert([
            'name' => 'Sujon Sorkar',
            'email' => 'sujon101@gmail.com',
            'mobile' => '01787408231',
            'blood_group' => 'O-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Sagor Pk',
            'email' => 'sagor1@sagor.com',
            'mobile' => '0178778231',
            'blood_group' => 'O-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Sagor Pk',
            'email' => 'sagor111@sagor.com',
            'mobile' => '0178778231',
            'blood_group' => 'O-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Sagor Pk',
            'email' => 'sagor11@sagor.com',
            'mobile' => '0178778231',
            'blood_group' => 'O-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Sagor Pk',
            'email' => 'sagor1110@sagor.com',
            'mobile' => '0178778231',
            'blood_group' => 'O-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Sagor Pk',
            'email' => 'sagor1111@sagor.com',
            'mobile' => '0178778231',
            'blood_group' => 'O-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Shuvo Primanik',
            'email' => 'shuvo1@shuvo.com',
            'mobile' => '01787788231',
            'blood_group' => 'O-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Sagor Sorkar',
            'email' => 'sagor1@sagor0.com',
            'mobile' => '01787788231',
            'blood_group' => 'O-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Polash Sorkar',
            'email' => 'polash1@polash.com',
            'mobile' => '01787407231',
            'blood_group' => 'O-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Joy Pk',
            'email' => 'joy1@joy.com',
            'mobile' => '01787407275',
            'blood_group' => 'O-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Sojib Sorkar',
            'email' => 'sojib1@sojib.com',
            'mobile' => '01787407296',
            'blood_group' => 'O-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Sowrav Das',
            'email' => 'sowrav1@sowrav.com',
            'mobile' => '01787407277',
            'blood_group' => 'O-',
            'country' => 'Bangladesh',
            'city' => 'Noakhali',
            'district' => 'Feni',
            'thana' => 'Feni',
            'area' => 'Feni',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Feni,Feni',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Fahad Ahmmed',
            'email' => 'fahad1@fahad.com',
            'mobile' => '01787407233',
            'blood_group' => 'O-',
            'country' => 'Bangladesh',
            'city' => 'Kumilla',
            'district' => 'Feni',
            'thana' => 'Kumilla',
            'area' => 'Kumilla',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Kumilla Sadar,Kumilla',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Munna Hossain',
            'email' => 'munna1@munna.com',
            'mobile' => '01787407279',
            'blood_group' => 'O-',
            'country' => 'Bangladesh',
            'city' => 'Feni',
            'district' => 'Feni',
            'thana' => 'Feni Sadar',
            'area' => 'Feni',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'HospitalMor,Feni',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);












        DB::table('users')->insert([
            'name' => 'Sujon Sorkar',
            'email' => 'sujon2@gmail.com',
            'mobile' => '01787408231',
            'blood_group' => 'AB+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Sagor Pk',
            'email' => 'sagor2@sagor.com',
            'mobile' => '0178778231',
            'blood_group' => 'AB+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Shuvo Primanik',
            'email' => 'shuvo2@shuvo.com',
            'mobile' => '01787788231',
            'blood_group' => 'AB+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Sagor Sorkar',
            'email' => 'sagor2@sagor0.com',
            'mobile' => '01787788231',
            'blood_group' => 'AB+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Sagor Sorkar',
            'email' => 'sagor22@sagor0.com',
            'mobile' => '01787788231',
            'blood_group' => 'AB+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Sagor Sorkar',
            'email' => 'sagor222@sagor0.com',
            'mobile' => '01787788231',
            'blood_group' => 'AB+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Sagor Sorkar',
            'email' => 'sagor2222@sagor0.com',
            'mobile' => '01787788231',
            'blood_group' => 'AB+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Polash Sorkar',
            'email' => 'polash2@polash.com',
            'mobile' => '01787407231',
            'blood_group' => 'AB+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Joy Pk',
            'email' => 'joy2@joy.com',
            'mobile' => '01787407275',
            'blood_group' => 'AB+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Sojib Sorkar',
            'email' => 'sojib2@sojib.com',
            'mobile' => '01787407296',
            'blood_group' => 'AB+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Sowrav Das',
            'email' => 'sowrav2@sowrav.com',
            'mobile' => '01787407277',
            'blood_group' => 'AB+',
            'country' => 'Bangladesh',
            'city' => 'Noakhali',
            'district' => 'Feni',
            'thana' => 'Feni',
            'area' => 'Feni',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Feni,Feni',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Fahad Ahmmed',
            'email' => 'fahad2@fahad.com',
            'mobile' => '01787407233',
            'blood_group' => 'AB+',
            'country' => 'Bangladesh',
            'city' => 'Kumilla',
            'district' => 'Feni',
            'thana' => 'Kumilla',
            'area' => 'Kumilla',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Kumilla Sadar,Kumilla',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Munna Hossain',
            'email' => 'munna2@munna.com',
            'mobile' => '01787407279',
            'blood_group' => 'AB+',
            'country' => 'Bangladesh',
            'city' => 'Feni',
            'district' => 'Feni',
            'thana' => 'Feni Sadar',
            'area' => 'Feni',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'HospitalMor,Feni',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);






        DB::table('users')->insert([
            'name' => 'Sujon Sorkar',
            'email' => 'sujon3@gmail.com',
            'mobile' => '01787408231',
            'blood_group' => 'AB-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Sagor Pk',
            'email' => 'sagor3@sagor.com',
            'mobile' => '0178778231',
            'blood_group' => 'AB-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Shuvo Primanik',
            'email' => 'shuvo3@shuvo.com',
            'mobile' => '01787788231',
            'blood_group' => 'AB-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Shuvo Primanik',
            'email' => 'shuvo33@shuvo.com',
            'mobile' => '01787788231',
            'blood_group' => 'AB-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Shuvo Primanik',
            'email' => 'shuvo333@shuvo.com',
            'mobile' => '01787788231',
            'blood_group' => 'AB-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Sagor Sorkar',
            'email' => 'sagor3@sagor0.com',
            'mobile' => '01787788231',
            'blood_group' => 'AB-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Polash Sorkar',
            'email' => 'polash300@polash.com',
            'mobile' => '01787407231',
            'blood_group' => 'AB-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Polash Sorkar',
            'email' => 'polash3@polash.com',
            'mobile' => '01787407231',
            'blood_group' => 'AB-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Polash Sorkar',
            'email' => 'polash33@polash.com',
            'mobile' => '01787407231',
            'blood_group' => 'AB-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Polash Sorkar',
            'email' => 'polash333@polash.com',
            'mobile' => '01787407231',
            'blood_group' => 'AB-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Joy Pk',
            'email' => 'joy3@joy.com',
            'mobile' => '01787407275',
            'blood_group' => 'AB-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Sojib Sorkar',
            'email' => 'sojib3@sojib.com',
            'mobile' => '01787407296',
            'blood_group' => 'AB-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Sowrav Das',
            'email' => 'sowrav3@sowrav.com',
            'mobile' => '01787407277',
            'blood_group' => 'AB-',
            'country' => 'Bangladesh',
            'city' => 'Noakhali',
            'district' => 'Feni',
            'thana' => 'Feni',
            'area' => 'Feni',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Feni,Feni',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Fahad Ahmmed',
            'email' => 'fahad3@fahad.com',
            'mobile' => '01787407233',
            'blood_group' => 'AB-',
            'country' => 'Bangladesh',
            'city' => 'Kumilla',
            'district' => 'Feni',
            'thana' => 'Kumilla',
            'area' => 'Kumilla',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Kumilla Sadar,Kumilla',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Munna Hossain',
            'email' => 'munna3@munna.com',
            'mobile' => '01787407279',
            'blood_group' => 'AB-',
            'country' => 'Bangladesh',
            'city' => 'Feni',
            'district' => 'Feni',
            'thana' => 'Feni Sadar',
            'area' => 'Feni',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'HospitalMor,Feni',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);










        DB::table('users')->insert([
            'name' => 'Sujon Sorkar',
            'email' => 'sujon5@gmail.com',
            'mobile' => '01787408231',
            'blood_group' => 'A+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Sagor Pk',
            'email' => 'sagor5@sagor.com',
            'mobile' => '0178778231',
            'blood_group' => 'A+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Sagor Pk',
            'email' => 'sagor55@sagor.com',
            'mobile' => '0178778231',
            'blood_group' => 'A+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Sagor Pk',
            'email' => 'sagor555@sagor.com',
            'mobile' => '0178778231',
            'blood_group' => 'A+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Sagor Pk',
            'email' => 'sagor5555@sagor.com',
            'mobile' => '0178778231',
            'blood_group' => 'A+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Shuvo Primanik',
            'email' => 'shuvo5@shuvo.com',
            'mobile' => '01787788231',
            'blood_group' => 'A+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Sagor Sorkar',
            'email' => 'sagor5@sagor0.com',
            'mobile' => '01787788231',
            'blood_group' => 'A+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Polash Sorkar',
            'email' => 'polash5@polash.com',
            'mobile' => '01787407231',
            'blood_group' => 'A+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Joy Pk',
            'email' => 'joy5@joy.com',
            'mobile' => '01787407275',
            'blood_group' => 'A+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Sojib Sorkar',
            'email' => 'sojib5@sojib.com',
            'mobile' => '01787407296',
            'blood_group' => 'A+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Sowrav Das',
            'email' => 'sowrav5@sowrav.com',
            'mobile' => '01787407277',
            'blood_group' => 'A+',
            'country' => 'Bangladesh',
            'city' => 'Noakhali',
            'district' => 'Feni',
            'thana' => 'Feni',
            'area' => 'Feni',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Feni,Feni',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Fahad Ahmmed',
            'email' => 'fahad5@fahad.com',
            'mobile' => '01787407233',
            'blood_group' => 'A+',
            'country' => 'Bangladesh',
            'city' => 'Kumilla',
            'district' => 'Feni',
            'thana' => 'Kumilla',
            'area' => 'Kumilla',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Kumilla Sadar,Kumilla',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Munna Hossain',
            'email' => 'munna5@munna.com',
            'mobile' => '01787407279',
            'blood_group' => 'A+',
            'country' => 'Bangladesh',
            'city' => 'Feni',
            'district' => 'Feni',
            'thana' => 'Feni Sadar',
            'area' => 'Feni',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'HospitalMor,Feni',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);











        DB::table('users')->insert([
            'name' => 'Sujon Sorkar',
            'email' => 'sujon6@gmail.com',
            'mobile' => '01787408231',
            'blood_group' => 'A-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Sagor Pk',
            'email' => 'sagor6@sagor.com',
            'mobile' => '0178778231',
            'blood_group' => 'A-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Shuvo Primanik',
            'email' => 'shuvo6@shuvo.com',
            'mobile' => '01787788231',
            'blood_group' => 'A-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Shuvo Primanik',
            'email' => 'shuvo66@shuvo.com',
            'mobile' => '01787788231',
            'blood_group' => 'A-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Shuvo Primanik',
            'email' => 'shuvo666@shuvo.com',
            'mobile' => '01787788231',
            'blood_group' => 'A-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Shuvo Primanik',
            'email' => 'shuvo6666@shuvo.com',
            'mobile' => '01787788231',
            'blood_group' => 'A-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Shuvo Primanik',
            'email' => 'shuvo66666@shuvo.com',
            'mobile' => '01787788231',
            'blood_group' => 'A-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Sagor Sorkar',
            'email' => 'sagor6@sagor0.com',
            'mobile' => '01787788231',
            'blood_group' => 'A-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Polash Sorkar',
            'email' => 'polash6@polash.com',
            'mobile' => '01787407231',
            'blood_group' => 'A-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Joy Pk',
            'email' => 'joy6@joy.com',
            'mobile' => '01787407275',
            'blood_group' => 'A-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Sojib Sorkar',
            'email' => 'sojib6@sojib.com',
            'mobile' => '01787407296',
            'blood_group' => 'A-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Sowrav Das',
            'email' => 'sowrav6@sowrav.com',
            'mobile' => '01787407277',
            'blood_group' => 'A-',
            'country' => 'Bangladesh',
            'city' => 'Noakhali',
            'district' => 'Feni',
            'thana' => 'Feni',
            'area' => 'Feni',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Feni,Feni',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Fahad Ahmmed',
            'email' => 'fahad6@fahad.com',
            'mobile' => '01787407233',
            'blood_group' => 'A-',
            'country' => 'Bangladesh',
            'city' => 'Kumilla',
            'district' => 'Feni',
            'thana' => 'Kumilla',
            'area' => 'Kumilla',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Kumilla Sadar,Kumilla',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Munna Hossain',
            'email' => 'munna6@munna.com',
            'mobile' => '01787407279',
            'blood_group' => 'A-',
            'country' => 'Bangladesh',
            'city' => 'Feni',
            'district' => 'Feni',
            'thana' => 'Feni Sadar',
            'area' => 'Feni',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'HospitalMor,Feni',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);












        DB::table('users')->insert([
            'name' => 'Sujon Sorkar',
            'email' => 'sujon7@gmail.com',
            'mobile' => '01787408231',
            'blood_group' => 'B+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Sagor Pk',
            'email' => 'sagor7@sagor.com',
            'mobile' => '0178778231',
            'blood_group' => 'B+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Shuvo Primanik',
            'email' => 'shuvo7@shuvo.com',
            'mobile' => '01787788231',
            'blood_group' => 'B+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Sagor Sorkar',
            'email' => 'sagor7@sagor0.com',
            'mobile' => '01787788231',
            'blood_group' => 'B+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Polash Sorkar',
            'email' => 'polash7@polash.com',
            'mobile' => '01787407231',
            'blood_group' => 'B+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Joy Pk',
            'email' => 'joy7@joy.com',
            'mobile' => '01787407275',
            'blood_group' => 'B+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Sojib Sorkar',
            'email' => 'sojib7@sojib.com',
            'mobile' => '01787407296',
            'blood_group' => 'B+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Sowrav Das',
            'email' => 'sowrav7@sowrav.com',
            'mobile' => '01787407277',
            'blood_group' => 'B+',
            'country' => 'Bangladesh',
            'city' => 'Noakhali',
            'district' => 'Feni',
            'thana' => 'Feni',
            'area' => 'Feni',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Feni,Feni',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Fahad Ahmmed',
            'email' => 'fahad700@fahad.com',
            'mobile' => '01787407233',
            'blood_group' => 'B+',
            'country' => 'Bangladesh',
            'city' => 'Kumilla',
            'district' => 'Feni',
            'thana' => 'Kumilla',
            'area' => 'Kumilla',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Kumilla Sadar,Kumilla',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Munna Hossain',
            'email' => 'munna700@munna.com',
            'mobile' => '01787407279',
            'blood_group' => 'B+',
            'country' => 'Bangladesh',
            'city' => 'Feni',
            'district' => 'Feni',
            'thana' => 'Feni Sadar',
            'area' => 'Feni',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'HospitalMor,Feni',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Munna Hossain',
            'email' => 'munna7000@munna.com',
            'mobile' => '01787407279',
            'blood_group' => 'B+',
            'country' => 'Bangladesh',
            'city' => 'Feni',
            'district' => 'Feni',
            'thana' => 'Feni Sadar',
            'area' => 'Feni',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'HospitalMor,Feni',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Munna Hossain',
            'email' => 'munna70000@munna.com',
            'mobile' => '01787407279',
            'blood_group' => 'B+',
            'country' => 'Bangladesh',
            'city' => 'Feni',
            'district' => 'Feni',
            'thana' => 'Feni Sadar',
            'area' => 'Feni',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'HospitalMor,Feni',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);








        DB::table('users')->insert([
            'name' => 'Sujon Sorkar',
            'email' => 'sujon8@gmail.com',
            'mobile' => '01787408231',
            'blood_group' => 'B-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Sagor Pk',
            'email' => 'sagor8@sagor.com',
            'mobile' => '0178778231',
            'blood_group' => 'B-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Shuvo Primanik',
            'email' => 'shuvo8@shuvo.com',
            'mobile' => '01787788231',
            'blood_group' => 'B-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Sagor Sorkar',
            'email' => 'sagor8@sagor0.com',
            'mobile' => '01787788231',
            'blood_group' => 'B-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Polash Sorkar',
            'email' => 'polash8@polash.com',
            'mobile' => '01787407231',
            'blood_group' => 'B-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Joy Pk',
            'email' => 'joy8@joy.com',
            'mobile' => '01787407275',
            'blood_group' => 'B-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Sojib Sorkar',
            'email' => 'sojib8@sojib.com',
            'mobile' => '01787407296',
            'blood_group' => 'B-',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Sowrav Das',
            'email' => 'sowrav8@sowrav.com',
            'mobile' => '01787407277',
            'blood_group' => 'B-',
            'country' => 'Bangladesh',
            'city' => 'Noakhali',
            'district' => 'Feni',
            'thana' => 'Feni',
            'area' => 'Feni',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Feni,Feni',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Fahad Ahmmed',
            'email' => 'fahad7@fahad.com',
            'mobile' => '01787407233',
            'blood_group' => 'B-',
            'country' => 'Bangladesh',
            'city' => 'Kumilla',
            'district' => 'Feni',
            'thana' => 'Kumilla',
            'area' => 'Kumilla',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Kumilla Sadar,Kumilla',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Munna Hossain',
            'email' => 'munna7@munna.com',
            'mobile' => '01787407279',
            'blood_group' => 'B-',
            'country' => 'Bangladesh',
            'city' => 'Feni',
            'district' => 'Feni',
            'thana' => 'Feni Sadar',
            'area' => 'Feni',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'HospitalMor,Feni',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);



        DB::table('users')->insert([
            'name' => 'Sowrav Das',
            'email' => 'sowrav@sowrav.com',
            'mobile' => '01787407277',
            'blood_group' => 'O+',
            'country' => 'Bangladesh',
            'city' => 'Noakhali',
            'district' => 'Feni',
            'thana' => 'Feni',
            'area' => 'Feni',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Feni,Feni',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Fahad Ahmmed',
            'email' => 'fahad@fahad.com',
            'mobile' => '01787407233',
            'blood_group' => 'O+',
            'country' => 'Bangladesh',
            'city' => 'Kumilla',
            'district' => 'Feni',
            'thana' => 'Kumilla',
            'area' => 'Kumilla',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Kumilla Sadar,Kumilla',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Munna Hossain',
            'email' => 'munna@munna.com',
            'mobile' => '01787407279',
            'blood_group' => 'O+',
            'country' => 'Bangladesh',
            'city' => 'Feni',
            'district' => 'Feni',
            'thana' => 'Feni Sadar',
            'area' => 'Feni',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'HospitalMor,Feni',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);



        DB::table('users')->insert([
            'name' => 'Sagor Pk',
            'email' => 'sagor@sagor.com',
            'mobile' => '0178778231',
            'blood_group' => 'O+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Shuvo Primanik',
            'email' => 'shuvo@shuvo.com',
            'mobile' => '01787788231',
            'blood_group' => 'O+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Sagor Sorkar',
            'email' => 'sagor0@sagor0.com',
            'mobile' => '01787788231',
            'blood_group' => 'O+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Polash Sorkar',
            'email' => 'polash@polash.com',
            'mobile' => '01787407231',
            'blood_group' => 'O+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Joy Pk',
            'email' => 'joy@joy.com',
            'mobile' => '01787407275',
            'blood_group' => 'O+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Sojib Sorkar',
            'email' => 'sojib@sojib.com',
            'mobile' => '01787407296',
            'blood_group' => 'O+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);
        DB::table('users')->insert([
            'name' => 'Sojib Sorkar',
            'email' => 'sojib00@sojib.com',
            'mobile' => '01787407296',
            'blood_group' => 'O+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Sujon Sorkar',
            'email' => 'sujon@gmail.com',
            'mobile' => '01787408231',
            'blood_group' => 'O+',
            'country' => 'Bangladesh',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);


        DB::table('users')->insert([
            'name' => 'Sujon Sorkar',
            'email' => 'sujon000000@gmail.com',
            'mobile' => '01787408231',
            'blood_group' => 'O+',
            'country' => 'india',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);

        DB::table('users')->insert([
            'name' => 'Sujon Sorkar',
            'email' => 'sujon00000@gmail.com',
            'mobile' => '01787408231',
            'blood_group' => 'O+',
            'country' => 'america',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);


        DB::table('users')->insert([
            'name' => 'Sujon Sorkar',
            'email' => 'sujon0000000@gmail.com',
            'mobile' => '01787408231',
            'blood_group' => 'O+',
            'country' => 'america',
            'city' => 'Natore',
            'district' => 'Natore',
            'thana' => 'Singra',
            'area' => 'Singra',
            'last_donate_time' => 'NULL',
            'state' => ' ',
            'address' => 'Singra,Natore',
            'status' => '0',
            'profile_picture' => 'NULL',
            'type' => 'doner',
            'password' => '$2y$10$0Jc/.Gmdw2ArK4OIhDAJjekmQHvkbyKejF6HHSuHX65dfhN0igbdK',
        ]);



















    }
}
